import { test, expect } from "@playwright/test";

test("feedback dashboard separates demo data and opens a three-column processing workspace", async ({ page }, testInfo) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("tab", { name: "反馈总览" })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator(".fd-hero")).toContainText("提升用餐体验");
  await page.getByLabel("反馈月份").fill("");
  const stats = page.getByLabel("真实反馈统计");
  const before = await stats.locator("strong").allTextContents();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath("feedback-overview.png") });
  const response = page.waitForResponse((item) => item.url().endsWith("/api/demo/actions"));
  await page.getByRole("button", { name: "加载示例 Action", exact: true }).click();
  const seeded = await (await response).json();
  expect(seeded.feedbackIds).toHaveLength(12);
  expect(seeded.actionIds).toHaveLength(4);
  await expect(page.getByRole("checkbox", { name: "示例反馈", exact: true })).toBeChecked();
  expect(await stats.locator("strong").allTextContents()).toEqual(before);
  const aggregate = page.getByRole("region", { name: "汇总改善事项", exact: true });
  await expect(aggregate).toContainText("12 条示例反馈");
  await expect(aggregate.locator(".fd-action-previews > button")).toHaveCount(4);
  await page.getByRole("tab", { name: "处理工作区" }).click();
  const workspace = page.getByRole("region", { name: "反馈处理工作区", exact: true });
  await expect(workspace.locator(".fd-inbox-list > button")).toHaveCount(12);
  await expect(workspace.getByRole("heading", { name: "反馈详情", exact: true })).toBeVisible();
  await expect(workspace).toContainText("示例反馈");
  await expect(workspace.locator(".fd-inbox-insights")).toContainText("待审改善事项");
  await expect(workspace.getByRole("button", { name: "批准 / Approve" })).toHaveCount(0);
  await workspace.getByLabel("工作区本次处理说明").fill("已核对示例反馈，待Action模块统一审批。");
  await workspace.getByRole("button", { name: "保存处理备注" }).click();
  await expect(page.locator('.toast[role="status"]')).toContainText("处理备注与状态已保存");
  await page.screenshot({ path: testInfo.outputPath("feedback-processing-workspace.png") });
  await aggregate.getByRole("button", { name: "进入 Action 模块", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Action 事项", exact: true })).toBeVisible();
  await expect(page.getByLabel("排菜员 Prompt")).toHaveCount(0);
  await page.getByRole("button", { name: "示例事项", exact: true }).click();
  await expect(page.locator(".action-card")).toHaveCount(4);
  const data = await (await page.request.get("/api/data")).json();
  expect(data.actions.filter((item) => item.demo)).toHaveLength(4);
  expect(data.actions.filter((item) => item.demo).every((item) => item.feedbackIds.length > 1)).toBeTruthy();
  expect(errors).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});

test("approved demo action affects simulated menu and can be reinspected without Azure calls", async ({ page }, testInfo) => {
  const errors = [];
  const externalRequests = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("request", (request) => { if (/azure\.com|openai\.com/i.test(request.url())) externalRequests.push(request.url()); });
  const before = await (await page.request.get("/api/data")).json();
  await page.goto("/");
  await page.getByRole("navigation").getByRole("button", { name: /Action 事项/ }).click();
  const seedResponse = page.waitForResponse((response) => response.url().endsWith("/api/demo/actions"));
  await page.getByRole("button", { name: "加载示例 Action", exact: true }).click();
  const seeded = await (await seedResponse).json();
  const preset = seeded.actions.find((action) => action.id === "A-demo-aggregate-prefer");
  expect(preset).toBeTruthy();
  const actionCard = page.locator(".action-card").filter({ hasText: preset.title });
  await actionCard.locator("summary").first().click();
  await expect(actionCard.getByLabel("排菜调整要求")).toHaveValue(preset.menuInstruction);
  const approvalResponse = page.waitForResponse((response) => response.url().endsWith(`/api/actions/${preset.id}`) && response.request().method() === "PATCH");
  await actionCard.getByRole("button", { name: "批准 / Approve" }).click();
  const approved = await (await approvalResponse).json();
  expect(approved.status).toBe("approved");
  expect(approved.menuInstruction).toBe(preset.menuInstruction);
  await expect(actionCard).toContainText("已批准");
  await page.getByRole("navigation").getByRole("button", { name: /六周菜单/ }).click();
  await page.getByRole("checkbox", { name: "模拟排菜测试（不调用 AI）", exact: true }).check();
  const generatedResponse = page.waitForResponse((response) => response.url().endsWith("/api/plans/generate"));
  await page.getByRole("button", { name: "一次生成全部档口六周菜单", exact: true }).click();
  const response = await generatedResponse;
  expect(response.request().postDataJSON()).toMatchObject({ demo: true, useAi: false });
  expect(response.ok()).toBeTruthy();
  const plan = await response.json();
  expect(plan.demo || plan.workflow.demo || plan.workflow.mode === "demo").toBeTruthy();
  const impact = plan.workflow.actionImpacts.find((item) => item.actionId === preset.id);
  expect(impact).toBeTruthy();
  expect(impact.revision).toBe(approved.revision);
  expect(impact.evidence.length).toBeGreaterThan(0);
  await expect(page.locator(".workflow-section")).toContainText("不调用 Azure AI");
  const impactCard = page.locator(".action-impacts > details").filter({ hasText: preset.title });
  await impactCard.locator("summary").click();
  await expect(impactCard).toContainText("本次选用");
  await expect(impactCard).toContainText("变化槽位");
  await page.screenshot({ path: testInfo.outputPath("demo-menu-action-impact.png") });
  const inspectedResponse = page.waitForResponse((response) => response.url().endsWith("/api/plans/inspect"));
  await page.getByRole("button", { name: "重新模拟检验", exact: true }).click();
  const inspected = await inspectedResponse;
  expect(inspected.request().postDataJSON().demo).toBe(true);
  expect(inspected.ok()).toBeTruthy();
  const checked = await inspected.json();
  expect(checked.workflow.inspectedAt).toBeTruthy();
  expect(checked.workflow.actionImpacts.some((item) => item.actionId === preset.id)).toBeTruthy();
  await expect(page.locator('.toast[role="status"]')).toContainText("检验员已完成重新检验");
  const after = await (await page.request.get("/api/data")).json();
  expect(after.aiStatus.calls).toBe(before.aiStatus.calls);
  expect(after.aiStatus.inputTokens).toBe(before.aiStatus.inputTokens);
  expect(after.aiStatus.outputTokens).toBe(before.aiStatus.outputTokens);
  expect(externalRequests).toEqual([]);
  expect(errors).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});
