import { test, expect } from "@playwright/test";

test("feedback reply, aggregate action approval, monthly wordcloud and revision history", async ({ page }, testInfo) => {
  const data = await (await page.request.get("/api/data")).json();
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const feedback = { id: "F-UI-WORKFLOW", date: "2026-08-28", restaurant: "全部档口", content: "前端工作流验收：希望增加清淡素菜", type: "建议", category: "口味", status: "未处理", channel: "测试", owner: "", summaryRecord: false, sources: [], events: [], replies: [] };
  const aiStatus = { configured: true, model: "test-model", budgetUsd: 150 };
  const secondFeedback = { ...feedback, id: "F-UI-SECOND", content: "前端工作流验收：午餐素菜选择较少" };
  const state = { ...data, feedback: [...data.feedback, feedback, secondFeedback], actions: [], aiStatus };
  let analysis = null;
  const json = (route, body) => route.fulfill({ json: body });
  await page.route("**/api/data", (route) => json(route, state));
  await page.route("**/api/feedback/F-UI-WORKFLOW/analyze", (route) => {
    feedback.aiAnalysis = { summary: "员工希望增加清淡素菜。", replyDraft: "感谢建议，将评估增加清淡素菜。", keywords: ["清淡", "素菜"] };
    return json(route, { feedback, actions: state.actions });
  });
  await page.route("**/api/actions/summary?*", (route) => json(route, { analysis, sourceCount: state.feedback.length, actions: state.actions }));
  await page.route("**/api/actions/summarize", (route) => {
    analysis = { id: "SUMMARY-UI-1", sourceCount: state.feedback.length, summary: "多条反馈共同建议增加清淡素菜。", createdAt: "2026-09-08T03:00:00Z" };
    state.actions = [{ id: "A-UI-1", feedbackIds: [feedback.id, secondFeedback.id], evidence: [{ feedbackId: feedback.id, quote: feedback.content }, { feedbackId: secondFeedback.id, quote: secondFeedback.content }], title: "增加清淡素菜", description: "评估每餐提供清淡素菜", targetStall: "全部档口", menuInstruction: "优先选用不辣素菜", priority: "medium", status: "pending", enabled: true, revision: 1, history: [] }];
    return json(route, { analysis, sourceCount: state.feedback.length, actions: state.actions });
  });
  await page.route("**/api/feedback/F-UI-WORKFLOW/reply", (route) => {
    feedback.replies.push({ id: "R-UI-1", text: route.request().postDataJSON().text, at: "2026-09-08T02:00:00Z" });
    return json(route, feedback);
  });
  await page.route("**/api/actions/A-UI-1", (route) => {
    const input = route.request().postDataJSON();
    const previous = state.actions[0];
    state.actions[0] = { ...previous, ...input, revision: previous.revision + 1, history: [...previous.history, { at: "2026-09-08T03:00:00Z", reason: input.reason, revision: previous.revision + 1, status: input.status || previous.status }] };
    return json(route, state.actions[0]);
  });
  await page.route("**/api/feedback/summary?*", (route) => {
    const month = new URL(route.request().url()).searchParams.get("month");
    return json(route, { month, total: month === "2026-08" ? 1 : 0, keywords: month === "2026-08" ? [{ text: "清淡", count: 3 }, { text: "素菜", count: 2 }] : [], summary: month === "2026-08" ? "本月主要关注清淡素菜。" : "该月暂无反馈", aiSummary: null });
  });
  await page.goto("/");
  await page.getByLabel("搜索反馈").fill(feedback.content);
  await page.getByRole("button", { name: "跟进", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByRole("button", { name: "AI 起草回复", exact: true }).click();
  await expect(dialog.getByLabel("反馈回复")).toHaveValue("感谢建议，将评估增加清淡素菜。");
  await dialog.getByLabel("反馈回复").fill("感谢建议，运营已收到，将评估增加清淡素菜。");
  await dialog.getByRole("button", { name: "保存回复" }).click();
  await expect(dialog.getByText("已保存回复 · 1")).toBeVisible();
  expect(state.actions).toHaveLength(0);
  await page.screenshot({ path: testInfo.outputPath("feedback-action.png") });
  await dialog.getByRole("button", { name: "关闭", exact: true }).click();
  await page.getByLabel("反馈月份").fill("2026-08");
  await page.getByRole("button", { name: "月度汇总", exact: true }).click();
  await expect(dialog.getByRole("img", { name: /反馈词云/ })).toBeVisible();
  await expect(dialog).toContainText("本月主要关注清淡素菜");
  await page.screenshot({ path: testInfo.outputPath("feedback-wordcloud.png") });
  await dialog.getByRole("button", { name: "关闭", exact: true }).click();
  await page.getByLabel("反馈月份").fill("2025-01");
  await page.getByRole("button", { name: "月度汇总", exact: true }).click();
  await expect(dialog).toContainText("该月暂无反馈，暂无词云或月度摘要");
  await dialog.getByRole("button", { name: "关闭", exact: true }).click();
  await page.locator(".fd-hero").getByRole("button").click();
  await expect(page.getByRole("heading", { name: "Action 事项", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "汇总反馈生成改善事项", exact: true }).click();
  const card = page.locator(".action-card");
  await expect(card).toContainText("2 条相关反馈");
  await card.locator("summary").first().click();
  await card.getByLabel("排菜调整要求").fill("午餐至少保留一种不辣素菜");
  await card.getByLabel("调整 / 审批理由").fill("本月反馈集中关注清淡菜");
  await card.getByRole("button", { name: "批准 / Approve" }).click();
  await expect(card).toContainText("已批准");
  expect(state.actions[0].menuInstruction).toBe("午餐至少保留一种不辣素菜");
  expect(state.actions[0].status).toBe("approved");
  expect(state.actions[0].revision).toBe(2);
  await card.locator("summary").first().click();
  await card.locator("summary").filter({ hasText: "调整记录" }).click();
  await expect(card).toContainText("本月反馈集中关注清淡菜");
  await expect(page.getByText(/Prompt/)).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("operations.png"), fullPage: true });
  expect(errors).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});

test("menu workflow shows inspector result, action evidence and trace", async ({ page }, testInfo) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const data = await (await page.request.get("/api/data")).json();
  const baseline = await (await page.request.post("/api/plans/generate", { data: { scope: "all", start: "2026-09-07", seed: 1, count: 4, meals: ["午餐"], useAi: false } })).json();
  const action = { id: "A-UI-PLAN", title: "增加清淡菜", targetStall: "全部档口", revision: 3, instruction: "优先清淡菜", status: "partial", baselineEntries: 10, selectedEntries: 14, changedEntries: 4, evidence: ["清淡菜槽位由 10 增加到 14。"] };
  baseline.workflow = { runId: "RUN-UI-1", status: "needs_review", promptVersion: 2, requiresHumanApproval: true, stale: false, planner: { summary: "已结合批准反馈和规则编排六周菜单。", unresolved: [] }, inspector: { verdict: "pass", summary: "清淡菜已增加，标签未知部分需运营确认。", findings: [] }, actionImpacts: [action], inspectedAt: "2026-09-08T05:00:00Z" };
  await page.route("**/api/data", (route) => route.fulfill({ json: { ...data, aiStatus: { configured: true, model: "test-model" }, actions: [{ ...action, status: "approved", enabled: true }] } }));
  let generation;
  await page.route("**/api/plans/generate", (route) => { generation = route.request().postDataJSON(); return route.fulfill({ json: baseline }); });
  await page.route("**/api/menu-runs/RUN-UI-1", (route) => route.fulfill({ json: { id: "RUN-UI-1", status: "needs_review", input: generation, snapshots: { actions: [action], rules: [] }, workflow: baseline.workflow } }));
  await page.goto("/");
  await page.getByRole("navigation").getByRole("button", { name: /六周菜单/ }).click();
  await page.getByRole("checkbox", { name: "启用 AI 排菜员与检验员" }).check();
  await page.getByRole("button", { name: "一次生成全部档口六周菜单" }).click();
  await expect(page.getByRole("heading", { name: "AI 检验通过 · 待人工审核" })).toBeVisible();
  expect(generation.useAi).toBe(true);
  await page.locator(".action-impacts > details > summary").click();
  await expect(page.locator(".action-impacts")).toContainText("清淡菜槽位由 10 增加到 14");
  await page.screenshot({ path: testInfo.outputPath("menu-workflow.png") });
  await page.getByRole("button", { name: "查看运行留痕" }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toContainText("RUN-UI-1");
  await dialog.locator("summary").filter({ hasText: "Action 快照" }).click();
  await expect(dialog).toContainText("增加清淡菜");
  await expect(dialog.getByText(/Prompt/)).toHaveCount(0);
  await dialog.getByRole("button", { name: "关闭", exact: true }).click();
  expect(errors).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});
